name: Docker Image CI

on:
  push:
    branches: [ "work/cicd" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - file: Dockerfile
            tag: latest
          - file: Dockerfile.alpine
            tag: alpine

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm

    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        platforms: ${{ steps.buildx.outputs.platforms }}
        file: ${{ matrix.file }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rpi-nginx-proxy:${{ matrix.tag }}
